import assets from "./assets";
const NFTData = [
  {
    id: "NFT-01",
    price: 4.25,
    name: "Cars #176",
    image: assets.cars1,
    countdown: '12h 30m',
    creator: "Putri Intan",
  },
  {
    id: "NFT-02",
    price: 7.25,
    name: "Cars #452",
    image: assets.cars2,
    countdown: '1h',
    creator: "Siti Nurhaliza",
  },
  {
    id: "NFT-03",
    price: 95.25,
    name: "Cars #301",
    image: assets.cars3,
    countdown: '22m',
    creator: "Putri Intan",
  },
  {
    id: "NFT-04",
    price: 54.25,
    name: "Cars #024",
    image: assets.cars4,
    countdown: '6h 29m',
    creator: "Siti Nurhaliza",
  },
  {
    id: "NFT-05",
    price: 10.25,
    name: "Cars #576",
    image: assets.cars5,
    countdown: '30s',
    creator: "Putri Intan",

  },
  {
    id: "NFT-06",
    price: 4.25,
    name: "Cars #666",
    image: assets.cars6,
    countdown: '1d 10h',
    creator: "Elisabeth aho",

  },
  {
    id: "NFT-07",
    price: 14.25,
    name: "Cars #371",
    image: assets.cars7,
    countdown: '10d 5h',
    creator: "Elisabeth aho",
  },
  {
    id: "NFT-08",
    price: 25,
    name: "Cars #098",
    image: assets.cars8,
    countdown: '15m',
    creator: "Siti Nurhaliza",
  },
  {
    id: "NFT-09",
    price: 7.95,
    name: "Cars #145",
    image: assets.cars9,
    countdown: '7d 1hr',
    creator: "Elisabeth aho",
  },
  {
    id: "NFT-010",
    price: 95.25,
    name: "Cars #100",
    image: assets.cars10,
    countdown: '50s',
    creator: "Elisabeth aho",
  },
  {
    id: "NFT-011",
    price: 511.25,
    name: "Cars #110",
    image: assets.cars11,
    countdown: '9h 55s',
    creator: "Elisabeth aho",
  },
  {
    id: "NFT-012",
    price: 10.212,
    name: "Cars #912",
    image: assets.cars12,
    countdown: '40m 10s',
    creator: "David doe",

  },
  {
    id: "NFT-013",
    price: 4.25,
    name: "Cars #613",
    image: assets.cars13,
    countdown: '9h 40m',
    creator: "David doe",

  },
  {
    id: "NFT-014",
    price: 14.25,
    name: "Cars #414",
    image: assets.cars14,
    countdown: '2d 5h',
    creator: "Leo Messi",
  },
  {
    id: "NFT-015",
    price: 4.25,
    name: "Cars #215",
    image: assets.cars15,
    countdown: '12d 6h',
    creator: "David doe",
  },
  {
    id: "NFT-016",
    price: 7.165,
    name: "Cars #169",
    image: assets.cars16,
    countdown: '55s',
    creator: "David doe",
  },
  {
    id: "NFT-017",
    price: 95.25,
    name: "Cars #187",
    image: assets.cars17,
    countdown: '2hr 49m',
    creator: "Leo Messi",
  },
  {
    id: "NFT-018",
    price: 518.25,
    name: "Cars #158",
    image: assets.cars18,
    countdown: '22m',
    creator: "David doe",
  },
  {
    id: "NFT-019",
    price: 10.219,
    name: "Cars #919",
    image: assets.cars19,
    countdown: '13d 5h',
    creator: "David doe",
  },
  {
    id: "NFT-020",
    price: 4.25,
    name: "Cars #201",
    image: assets.cars20,
    countdown: '44m',
    creator: "David doe",

  },
  {
    id: "NFT-021",
    price: 14.25,
    name: "Cars #281",
    image: assets.cars21,
    countdown: '8d 45m',
    creator: "Leo Messi",
  },
  {
    id: "NFT-022",
    price: 25,
    name: "Cars #022",
    image: assets.cars22,
    countdown: '5s',
    creator: "Leo Messi",
  },
  {
    id: "NFT-023",
    price: 7.235,
    name: "Cars #203",
    image: assets.cars23,
    countdown: '60m',
    creator: "Leo Messi",
  },
  {
    id: "NFT-024",
    price: 95.25,
    name: "Cars #240",
    image: assets.cars24,
    countdown: '24m 5s',
    creator: "Leo Messi",
  },
  {
    id: "NFT-025",
    price: 525.25,
    name: "Cars #025",
    image: assets.cars25,
    countdown: '8s',
    creator: "Siti Nurhaliza",
  },
  {
    id: "NFT-026",
    price: 10.226,
    name: "Cars #426",
    image: assets.cars26,
    countdown: '10d 9h',
    creator: "Siti Nurhaliza",

  },
  {
    id: "NFT-027",
    price: 4.25,
    name: "Cars #207",
    image: assets.cars27,
    countdown: '24h',
    creator: "Siti Nurhaliza",

  },
  {
    id: "NFT-028",
    price: 28.25,
    name: "Cars #208",
    image: assets.cars28,
    countdown: '55m',
    creator: "David doe",
  },
  {
    id: "NFT-029",
    price: 4.25,
    name: "Cars #029",
    image: assets.cars29,
    countdown: '6s',
    creator: "David doe",
  },
  {
    id: "NFT-030",
    price: 7.305,
    name: "Cars #300",
    image: assets.cars30,
    countdown: '30m',
    creator: "David doe",
  },
  {
    id: "NFT-031",
    price: 95.25,
    name: "Cars #317",
    image: assets.cars31,
    countdown: '17d 2h',
    creator: "Elisabeth aho",
  },
  {
    id: "NFT-032",
    price: 532.25,
    name: "Cars #302",
    image: assets.cars32,
    countdown: '40d 23h',
    creator: "Elisabeth aho",
  },
  {
    id: "NFT-033",
    price: 10.233,
    name: "Cars #033",
    image: assets.cars33,
    countdown: '4d 5s',
    creator: "Elisabeth aho",

  },
  {
    id: "NFT-034",
    price: 4.25,
    name: "Cars #685",
    image: assets.cars34,
    countdown: '34h 35m',
    creator: "Leo Messi",

  },
  {
    id: "NFT-035",
    price: 14.25,
    name: "Cars #395",
    image: assets.cars35,
    countdown: '5m',
    creator: "Leo Messi",
  },
  {
    id: "NFT-036",
    price: 25,
    name: "Cars #736",
    image: assets.cars36,
    countdown: '7h 36m',
    creator: "Siti Nurhaliza",
  },
  {
    id: "NFT-037",
    price: 7.95,
    name: "Rhino #199",
    image: assets.rhino1,
    countdown: '22h 5m',
    creator: "Leo Messi",
  },
  {
    id: "NFT-038",
    price: 7.95,
    name: "Rhino #255",
    image: assets.rhino2,
    countdown: '25d 6m',
    creator: "Siti Nurhaliza",
  },
  {
    id: "NFT-039",
    price: 7.95,
    name: "Rhino #003",
    image: assets.rhino3,
    countdown: '30m',
    creator: "Siti Nurhaliza",
  },
  {
    id: "NFT-040",
    price: 7.95,
    name: "Rhino #403",
    image: assets.rhino4,
    countdown: '8d 5h',
    creator: "Leo Messi",

  },
  {
    id: "NFT-041",
    price: 7.95,
    name: "Rhino #145",
    image: assets.rhino5,
    countdown: '14m 55s',
    creator: "David doe",

  },
  {
    id: "NFT-042",
    price: 7.95,
    name: "Rhino #060",
    image: assets.rhino6,
    countdown: '10m 59s',
    creator: "David doe",
  },
  {
    id: "NFT-043",
    price: 7.95,
    name: "Rhino #007",
    image: assets.rhino7,
    countdown: '7d 7h',
    creator: "David doe",
  },
  {
    id: "NFT-044",
    price: 7.95,
    name: "Rhino #918",
    image: assets.rhino8,
    countdown: '3m 8s',
    creator: "David doe",
  },
  {
    id: "NFT-045",
    price: 7.95,
    name: "Rhino #9",
    image: assets.rhino9,
    countdown: '45m 10s',
    creator: "Leo Messi",
  },
  {
    id: "NFT-046",
    price: 7.95,
    name: "Rhino #180",
    image: assets.rhino10,
    countdown: '8d 13h',
    creator: "Elisabeth aho",

  },
  {
    id: "NFT-047",
    price: 7.95,
    name: "Rhino #101",
    image: assets.rhino11,
    countdown: '14d 45m',
    creator: "Elisabeth aho",

  },
  {
    id: "NFT-048",
    price: 7.95,
    name: "Rhino #012",
    image: assets.rhino12,
    countdown: '40s',
    creator: "Elisabeth aho",
  },
  {
    id: "NFT-049",
    price: 7.95,
    name: "Rhino #193",
    image: assets.rhino13,
    countdown: '19m 45s',
    creator: "Leo Messi",
  },
  {
    id: "NFT-050",
    price: 7.95,
    name: "Rhino #640",
    image: assets.rhino14,
    countdown: '1hr 0s',
    creator: "Victor de la Cruz",
  },
  {
    id: "NFT-051",
    price: 7.95,
    name: "Rhino #715",
    image: assets.rhino15,
    countdown: '2d 40s',
    creator: "David doe",
  },
  {
    id: "NFT-052",
    price: 7.95,
    name: "Rhino #196",
    image: assets.rhino16,
    countdown: '22h 6m',
    creator: "David doe",

  },
  {
    id: "NFT-053",
    price: 7.95,
    name: "Rhino #417",
    image: assets.rhino17,
    countdown: '5hr 40m',
    creator: "David doe",

  },
  {
    id: "NFT-054",
    price: 7.95,
    name: "Rhino #198",
    image: assets.rhino18,
    countdown: '1hr 0s',
    creator: "Victor de la Cruz",
  },
  {
    id: "NFT-055",
    price: 7.95,
    name: "Rhino #019",
    image: assets.rhino19,
    countdown: '4hr 33m',
    creator: "Victor de la Cruz",
  },
  {
    id: "NFT-056",
    price: 7.95,
    name: "Rhino #280",
    image: assets.rhino20,
    countdown: '22hr 50s',
    creator: "Victor de la Cruz",
  },
  {
    id: "NFT-057",
    price: 7.95,
    name: "Rhino #521",
    image: assets.rhino21,
    countdown: '6d 27m',
    creator: "Victor de la Cruz",
  },
  {
    id: "NFT-058",
    price: 7.95,
    name: "Rhino #220",
    image: assets.rhino22,
    countdown: '1hr 0s',
    creator: "Victor de la Cruz",

  },
  {
    id: "NFT-059",
    price: 7.95,
    name: "Rhino #623",
    image: assets.rhino23,
    countdown: '1d 0s',
    creator: "Victor de la Cruz",

  },
  {
    id: "NFT-060",
    price: 7.95,
    name: "Rhino #524",
    image: assets.rhino24,
    countdown: '33m 4s',
    creator: "Victor de la Cruz",
  },
  {
    id: "NFT-061",
    price: 7.95,
    name: "Rhino #255",
    image: assets.rhino25,
    countdown: '1hr 0s',
    creator: "Elisabeth aho",
  },
  {
    id: "NFT-062",
    price: 7.95,
    name: "Rhino #296",
    image: assets.rhino26,
    countdown: '45hr 0s',
    creator: "Elisabeth aho",
  },
  {
    id: "NFT-063",
    price: 7.95,
    name: "Rhino #367",
    image: assets.rhino27,
    countdown: '36m 4s',
    creator: "Elisabeth aho",
  },
  {
    id: "NFT-064",
    price: 7.95,
    name: "Rhino #289",
    image: assets.rhino28,
    countdown: '19m 0s',
    creator: "Elisabeth aho",

  },
  {
    id: "NFT-065",
    price: 7.95,
    name: "Rhino #209",
    image: assets.rhino29,
    countdown: '18hr 0s',
    creator: "Victor de la Cruz",

  },
  {
    id: "NFT-066",
    price: 7.95,
    name: "Rhino #430",
    image: assets.rhino30,
    countdown: '0s',
    creator: "Victor de la Cruz",
  },
  {
    id: "NFT-067",
    price: 7.95,
    name: "Rhino #319",
    image: assets.rhino31,
    countdown: '1hr 46m',
    creator: "Victor de la Cruz",
  },
  {
    id: "NFT-068",
    price: 7.95,
    name: "Rhino #432",
    image: assets.rhino32,
    countdown: '30m 8s',
    creator: "Victor de la Cruz",
  },
  {
    id: "NFT-069",
    price: 7.95,
    name: "Rhino #333",
    image: assets.rhino33,
    countdown: '22m 0s',
    creator: "Putri Intan",
  },
  {
    id: "NFT-070",
    price: 7.95,
    name: "Rhino #634",
    image: assets.rhino34,
    countdown: '55m 29s',
    creator: "Putri Intan",

  },
  {
    id: "NFT-071",
    price: 7.95,
    name: "Rhino #035",
    image: assets.rhino35,
    countdown: '60s',

    creator: "Putri Intan",
  },
  {
    id: "NFT-072",
    price: 7.95,
    name: "Rhino #356",
    image: assets.rhino36,
    countdown: '45m 0s',
    creator: "Putri Intan",
  },
];

export { NFTData };
